### PR TITLE
chore: Std.Tactic.Lint --> Batteries.Tactic.Lint

### PR DESCRIPTION
**Pull request by adomani**
I noticed this, looking for the `dupNamespace` linter.

---

Replacement done using
```bash
git ls-files '*.lean' | xargs sed -i 's=Std.Tactic.Lint=Batteries.Tactic.Lint='
```
and then looking for `open .*Std` in the `Tactic.Lint` files.

### CODE REVIEW

**Comment by adomani** [comment]
awaiting-review

**Review by grunweg — APPROVED** [review]
This is a subset of #887, but I also approve of this PR :-)

**Comment by grunweg** [comment]
With #887 having landed, this PR can be closed, right?

**Comment by mattrobball** [comment]
@adomani is there any thing left now? Thanks.

**Comment by grunweg** [comment]
With #887 having landed, this PR can be closed, right?

**Comment by adomani** [comment]
I'll close this PR, thanks!  I merge upstream and there are no further changes!

**Pull request closed without merging**
