### PR TITLE
Array changes corresponding to changes in Vector PR.

### PR DESCRIPTION
**Pull request by Shreyas4991**
This PR adds functions and theorems to the array API that were found necessary in #793 or useful from it.#793 

- [ ] Depends on PR #793

### CODE REVIEW

**Comment by fgdorais** [comment]
This PR doesn't actually depend on #793. The second commit is completely independent and the first commit shouldn't be there at all.

**Comment by Shreyas4991** [comment]
awaiting-review

**Comment by Shreyas4991** [comment]
> This PR doesn't actually depend on #793. The second commit is completely independent and the first commit shouldn't be there at all.

Yeah you're right. There is no dependency on 793 for these functions. How do I change this?

**Comment by fgdorais** [comment]
Git cherry picking would be the trick but since there is no history here, might as well close this PR and make a new one.

**Pull request closed without merging**
