### PR TITLE
refactor: add List.finRange and Array.finRange

### PR DESCRIPTION
**Pull request by fgdorais**
Harmonize with Mathlib, renaming Fin.list to List.finRange and Fin.enum to Array.finRange.

### CODE REVIEW

**Comment by fgdorais** [comment]
This is a second attempt at #899. The Mathlib breakages are too much for now. On hiatus.

**Comment by kim-em** [comment]
Perhaps it would be easier to change the definition in Mathlib first? I appreciate that this situation is super annoying.

We could also just rename Mathlib's definition to `finRange'` and then gradually switch it over.

(I am quite keen to have `finRange` fixed soon, so I am happy to help work on this.)

**Comment by fgdorais** [comment]
Help is more than welcome! It looks like it needs a long work window to resolve the Mathlib issues, I don't see such a long window until mid December. I'm also happy with your proposed workaround, if Mathlib folks are on board.

**Comment by kim-em** [comment]
@fgdorais, the Mathlib PR changing the definition of `finRange` has landed (note that it uses `ofFn fun x => x`, not `ofFn id`!).

Would you like to try again here? I'm very keen to have this in.

**Comment by fgdorais** [comment]
In progress.

**Pull request merged**
